<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Citizen;

class CitizensSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // ==================================================
            // KELUARGA 1 — Patimban RW 01
            // ==================================================
            [
                'nik' => '3276010101010001',
                'no_kk' => '3276010101010000',
                'nama' => 'Ahmad Sulaiman',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Patimban',
                'tanggal_lahir' => '1990-05-12',
                'agama' => 'Islam',
                'pendidikan_dalam_kk' => 'SMA',
                'pendidikan_sedang_ditempuh' => null,
                'pekerjaan' => 'Wiraswasta',
                'status_perkawinan' => 'Kawin',
                'hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Patimban',
                'rw' => '01',
                'rt' => '001',
                'alamat' => 'Dusun Patimban RT 001 RW 01',
                'alamat_sekarang' => 'Dusun Patimban RT 001 RW 01',
                'status_dasar' => 'aktif',
                'suku' => null,
                'latitude' => null,
                'longitude' => null,
                'keterangan' => 'Data demo',
            ],
            [
                'nik' => '3276010101010002',
                'no_kk' => '3276010101010000',
                'nama' => 'Siti Rahmawati',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Patimban',
                'tanggal_lahir' => '1993-08-22',
                'agama' => 'Islam',
                'pendidikan_dalam_kk' => 'SMA',
                'pendidikan_sedang_ditempuh' => null,
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'Kawin',
                'hubungan_dalam_keluarga' => 'Istri',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Patimban',
                'rw' => '01',
                'rt' => '001',
                'alamat' => 'Dusun Patimban RT 001 RW 01',
                'alamat_sekarang' => 'Dusun Patimban RT 001 RW 01',
                'status_dasar' => 'aktif',
                'suku' => null,
                'latitude' => null,
                'longitude' => null,
                'keterangan' => 'Data demo',
            ],
            [
                'nik' => '3276010101010007',
                'no_kk' => '3276010101010000',
                'nama' => 'Fajar Maulana',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Patimban',
                'tanggal_lahir' => '2015-02-10',
                'agama' => 'Islam',
                'pendidikan_dalam_kk' => 'SD',
                'pendidikan_sedang_ditempuh' => 'SD',
                'pekerjaan' => 'Pelajar',
                'status_perkawinan' => 'Belum Kawin',
                'hubungan_dalam_keluarga' => 'Anak',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Patimban',
                'rw' => '01',
                'rt' => '001',
                'alamat' => 'Dusun Patimban RT 001 RW 01',
                'alamat_sekarang' => 'Dusun Patimban RT 001 RW 01',
                'status_dasar' => 'aktif',
                'suku' => null,
                'latitude' => null,
                'longitude' => null,
                'keterangan' => 'Data demo',
            ],

            // ==================================================
            // KELUARGA 2 — Terungtum RW 02
            // ==================================================
            [
                'nik' => '3276010101010003',
                'no_kk' => '3276010101010003',
                'nama' => 'Budi Santoso',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Subang',
                'tanggal_lahir' => '2001-01-15',
                'agama' => 'Islam',
                'pendidikan_dalam_kk' => 'SMA',
                'pendidikan_sedang_ditempuh' => 'Kuliah',
                'pekerjaan' => 'Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Terungtum',
                'rw' => '02',
                'rt' => '004',
                'alamat' => 'Dusun Terungtum RT 004 RW 02',
                'alamat_sekarang' => 'Dusun Terungtum RT 004 RW 02',
                'status_dasar' => 'aktif',
                'suku' => null,
                'latitude' => null,
                'longitude' => null,
                'keterangan' => 'Data demo',
            ],
            [
                'nik' => '3276010101010008',
                'no_kk' => '3276010101010003',
                'nama' => 'Dina Lestari',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Subang',
                'tanggal_lahir' => '2003-06-18',
                'agama' => 'Islam',
                'pendidikan_dalam_kk' => 'SMA',
                'pendidikan_sedang_ditempuh' => 'Kuliah',
                'pekerjaan' => 'Mahasiswa',
                'status_perkawinan' => 'Belum Kawin',
                'hubungan_dalam_keluarga' => 'Adik',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Terungtum',
                'rw' => '02',
                'rt' => '004',
                'alamat' => 'Dusun Terungtum RT 004 RW 02',
                'alamat_sekarang' => 'Dusun Terungtum RT 004 RW 02',
                'status_dasar' => 'aktif',
                'suku' => null,
                'latitude' => null,
                'longitude' => null,
                'keterangan' => 'Data demo',
            ],

            // ==================================================
            // KELUARGA 3 — Genteng RW 03
            // ==================================================
            [
                'nik' => '3276010101010004',
                'no_kk' => '3276010101010004',
                'nama' => 'Rina Kurniasih',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Subang',
                'tanggal_lahir' => '1985-11-03',
                'agama' => 'Islam',
                'pendidikan_dalam_kk' => 'Diploma',
                'pendidikan_sedang_ditempuh' => null,
                'pekerjaan' => 'Guru Honorer',
                'status_perkawinan' => 'Kawin',
                'hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Genteng',
                'rw' => '03',
                'rt' => '007',
                'alamat' => 'Dusun Genteng RT 007 RW 03',
                'alamat_sekarang' => 'Dusun Genteng RT 007 RW 03',
                'status_dasar' => 'aktif',
                'suku' => null,
                'latitude' => null,
                'longitude' => null,
                'keterangan' => 'Data demo',
            ],
            [
                'nik' => '3276010101010009',
                'no_kk' => '3276010101010004',
                'nama' => 'Agus Prabowo',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Subang',
                'tanggal_lahir' => '1983-09-14',
                'agama' => 'Islam',
                'pendidikan_dalam_kk' => 'SMA',
                'pendidikan_sedang_ditempuh' => null,
                'pekerjaan' => 'Buruh',
                'status_perkawinan' => 'Kawin',
                'hubungan_dalam_keluarga' => 'Suami',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Genteng',
                'rw' => '03',
                'rt' => '007',
                'alamat' => 'Dusun Genteng RT 007 RW 03',
                'alamat_sekarang' => 'Dusun Genteng RT 007 RW 03',
                'status_dasar' => 'aktif',
                'suku' => null,
                'latitude' => null,
                'longitude' => null,
                'keterangan' => 'Data demo',
            ],

            // ==================================================
            // PENDUDUK TAMBAHAN (INDIVIDU)
            // ==================================================
            [
                'nik' => '3276010101010010',
                'no_kk' => '3276010101010010',
                'nama' => 'Hendra Wijaya',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Indramayu',
                'tanggal_lahir' => '1978-04-01',
                'agama' => 'Islam',
                'pendidikan_dalam_kk' => 'SMP',
                'pendidikan_sedang_ditempuh' => null,
                'pekerjaan' => 'Nelayan',
                'status_perkawinan' => 'Kawin',
                'hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Pantai',
                'rw' => '04',
                'rt' => '002',
                'alamat' => 'Dusun Pantai RT 002 RW 04',
                'alamat_sekarang' => 'Dusun Pantai RT 002 RW 04',
                'status_dasar' => 'aktif',
                'suku' => null,
                'latitude' => null,
                'longitude' => null,
                'keterangan' => 'Data demo',
            ],
            [
                'nik' => '3276010101010011',
                'no_kk' => '3276010101010011',
                'nama' => 'Nur Aini',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Indramayu',
                'tanggal_lahir' => '1980-12-09',
                'agama' => 'Islam',
                'pendidikan_dalam_kk' => 'SMP',
                'pendidikan_sedang_ditempuh' => null,
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'Kawin',
                'hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Pantai',
                'rw' => '04',
                'rt' => '003',
                'alamat' => 'Dusun Pantai RT 003 RW 04',
                'alamat_sekarang' => 'Dusun Pantai RT 003 RW 04',
                'status_dasar' => 'aktif',
                'suku' => null,
                'latitude' => null,
                'longitude' => null,
                'keterangan' => 'Data demo',
            ],
            [
                'nik' => '3276010101010012',
                'no_kk' => '3276010101010012',
                'nama' => 'Rizky Ananda',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '1999-07-07',
                'agama' => 'Islam',
                'pendidikan_dalam_kk' => 'S1',
                'pendidikan_sedang_ditempuh' => null,
                'pekerjaan' => 'Programmer',
                'status_perkawinan' => 'Belum Kawin',
                'hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Tengah',
                'rw' => '05',
                'rt' => '006',
                'alamat' => 'Dusun Tengah RT 006 RW 05',
                'alamat_sekarang' => 'Dusun Tengah RT 006 RW 05',
                'status_dasar' => 'aktif',
                'suku' => null,
                'latitude' => null,
                'longitude' => null,
                'keterangan' => 'Data demo',
            ],
            [
                'nik' => '3276010101010013',
                'no_kk' => '3276010101010013',
                'nama' => 'Lina Marlina',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2000-10-19',
                'agama' => 'Islam',
                'pendidikan_dalam_kk' => 'SMA',
                'pendidikan_sedang_ditempuh' => null,
                'pekerjaan' => 'Karyawan',
                'status_perkawinan' => 'Belum Kawin',
                'hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Tengah',
                'rw' => '05',
                'rt' => '007',
                'alamat' => 'Dusun Tengah RT 007 RW 05',
                'alamat_sekarang' => 'Dusun Tengah RT 007 RW 05',
                'status_dasar' => 'aktif',
                'suku' => null,
                'latitude' => null,
                'longitude' => null,
                'keterangan' => 'Data demo',
            ],
            [
                'nik' => '3276010101010014',
                'no_kk' => '3276010101010014',
                'nama' => 'Dewi Anggraini',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Majalengka',
                'tanggal_lahir' => '1995-03-27',
                'agama' => 'Islam',
                'pendidikan_dalam_kk' => 'S1',
                'pendidikan_sedang_ditempuh' => null,
                'pekerjaan' => 'Perawat',
                'status_perkawinan' => 'Belum Kawin',
                'hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'kewarganegaraan' => 'WNI',
                'dusun' => 'Utara',
                'rw' => '06',
                'rt' => '002',
                'alamat' => 'Dusun Utara RT 002 RW 06',
                'alamat_sekarang' => 'Dusun Utara RT 002 RW 06',
                'status_dasar' => 'aktif',
                'suku' => null,
                'latitude' => null,
                'longitude' => null,
                'keterangan' => 'Data demo',
            ],
        ];

        foreach ($data as $item) {
            Citizen::updateOrCreate(
                ['nik' => $item['nik']],
                $item
            );
        }
    }
}
